### ISSUE TITLE
Fatal Error on Plugin Activation

### ISSUE THREAD

**Issue by RicCastelhano** [ratedam/log-custom-favourites#1]
While activating the plugin, this fatal error is thrown:

`Warning: require_once(/srv/www/wordpress-default/wp-content/plugins/log-custom-favourites/classes\LOG_BackofficeHandler.php): failed to open stream: No such file or directory in /srv/www/wordpress-default/wp-content/plugins/log-custom-favourites/log-custom-favourites.php on line 36`

**Comment by ratedam** [comment]
Hello,

Updated with the fix.
